import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>
        {`
          h2 {
            font-size: 22px;
          }
        `}
      </style>

      <main className={styles.main}>
        <h1 className={styles.title}>&lt;Welcome to iBlogging/&gt;</h1>
        <div className={styles.imageWrap}>
          {/* <Image
            className={styles.homeImg}
            src="/homeimg.png"
            width={300}
            height={200}
          /> */}
          <img
            src="/homeimg.png"
            className={styles.homeImg}
            width={300}
            height={200}
            alt="iBlogger"
          />
        </div>
        <p className={styles.description}>One place for every iBlogger</p>

        {/* <div className={styles.blog}>
          <h2>Mostly Viewed Blogs</h2>
          <div className={styles.blogs}>
            <h3>Apple new release</h3>
            <p>The new release of apple SE 2022 Edition</p>
          </div>

          <div className={styles.blogs}>
            <h3>Apple new release</h3>
            <p>The new release of apple SE 2022 Edition</p>
          </div>

          <div className={styles.blogs}>
            <h3>Apple new release</h3>
            <p>The new release of apple SE 2022 Edition</p>
          </div>

          <div className={styles.blogs}>
            <h3>Apple new release</h3>
            <p>The new release of apple SE 2022 Edition</p>
          </div>
        </div> */}

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Apple new release &rarr;</h2>
            <p>The new release of apple SE 2022 Edition...</p>
          </a>

          <a className={styles.card}>
            <h2>Apple iPhone 13 mini &rarr;</h2>
            <p>A dramatically more powerful camera system...</p>
          </a>

          <a className={styles.card}>
            <h2>Apple iPhone 13 Pro &rarr;</h2>
            <p>A dramatically more powerful camera system...</p>
          </a>

          <a className={styles.card}>
            <h2>Apple Watch 7 &rarr;</h2>
            <p>
              Apple Watch Series 7, Apple Watch SE and Apple Watch Series...
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
